global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shortened-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8889'] 
- job_name: 'shortened-service'
    static_configs:
      - targets: ['shortened:8081']


