name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: 'package-lock.json'
      - name: Rename env.example to .env
        run: mv env.example .env
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      - name: Build the project
        run: |
          npm run build
      - name: Run unit tests
        run: |
          npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Configure Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.9.0
        with:
          version: 'latest'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/nestjs-app:latest .
      - name: Push Docker image to Google Container Registry
        run: |
          echo ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }} | base64 --decode > ${HOME}/gcloud-keyfile.json
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-keyfile.json
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/nestjs-app:latest
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy nestjs-app \
            --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/nestjs-app:latest \
            --platform managed \
            --region ${{ secrets.GOOGLE_CLOUD_REGION }} \
            --allow-unauthenticated
