name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: nestjs-api-374517
  GAR_NAME: nest-demo
  GAR_LOCATION: us-central1
  SERVICE: shortened-app
  REGION: us-central1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: "package-lock.json"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build the project
        run: npm run build
      - name: Run unit tests
        run: npm run test

  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Docker Auth
        run: gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=6379
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=1h
            BCRYPT_COST=10
            PORT=8080
            OTEL_SERVICE_NAME=shortened-service
            OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
      - name: Update BASE_URL after deployment
        run: |
            BASE_URL=$(gcloud run services describe shortened-app --region ${{ env.REGION }} --format='value(status.url)')
            echo "BASE_URL=$BASE_URL" >> .env
            gcloud run deploy shortened-app --image "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}" --region ${{ env.REGION }} --update-env-vars "BASE_URL=$BASE_URL"
