name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: 'latest'
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/nestjs-app:latest .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/nestjs-app:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GOOGLE_SERVICE_NAME }} \
            --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/nestjs-app:latest \
            --region ${{ secrets.GOOGLE_CLOUD_REGION }} \
            --platform managed \
            --allow-unauthenticated
